# Use a imagem base do Python
FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de requisitos e instala as dependências
COPY app/requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copia o código da aplicação
COPY app/ .

# Expõe a porta que a aplicação Flask irá rodar
EXPOSE 5000

# Define o comando para iniciar a aplicação
CMD ["python", "app.py"]
